GET http://localhost:8080/rest_snippets_war_exploded/api/movie/
Accept: application/json

###
GET http://localhost:8080/rest_snippets_war_exploded/api/movie/2
Accept: application/json

###
GET http://localhost:8080/rest_snippets_war_exploded/api/movie/99999999
Accept: application/json

###
POST http://localhost:8080/rest_snippets_war_exploded/movie/parent
Content-Type: application/json

{"year": 2001, "title": "Alle for to"}

###
PUT http://localhost:8080/rest_snippets_war_exploded/api/movie/2
Content-Type: application/json

{"year": 2006, "title": "Den nye film"}

###
DELETE http://localhost:8080/rest_snippets_war_exploded/api/movie/2
Content-Type: application/json
